### ISSUE TITLE
70th online meetup, 2022-03-19 with special promotion: `Choux Cream Latte`

### ISSUE THREAD

**Issue by jongfeel** [ThinkAboutSoftware/OnlineSelfCodingGroup#108]
https://meet.google.com/jyx-mxnq-kpk

### 참여 방법:

Assignees에 자신의 github 계정을 self로 추가
2시간 분량의 할 내용에 대해 댓글 작성 (최소 모임 시작 전까지)
빛의 속도 혹은 (주말, 휴일 포함) 최소 3일 내에 구글 캘린더 등록 메일 확인
모임 시간에 각자 개발 관련된 공부 진행

- 시작: 10시 30분
- 할 것 이야기: 5분 ~ 10분 간 진행
- 진행: 2시간, 하지만 쉬는 시간 및 기타 잡일 감안해서 1시간 ~ 1시간 30분 정도로 진행
- 한 것 이야기: 최대한 12시 40분까지, 조금 오버할 수 있음 (오래 하면 30분 얘기하기도 함)

모임 끝난 후 공부한 내용 정리 & 링크 추가 => 최소 다음 모각코 전까지 확인 가능해야 함.

**주의: 회사일 혹은 마감 기한 임박한 일 처리의 경우는 최대한 자제해 주세요. 주말 아침에 일하면 우울하니까요. ㅜㅜ**

---

70회 까지 왔습니다. 
69회때 사실 아무도 없어서 모각코는 폭파가 되긴 했습니다.
생각해보면 제가 하고 싶은 모각코인데 제가 폭파 하는 게 의미가 있나 싶습니다.
그래서 아무도 오지 않아도 제가 죽을 때 까지, 혹은 github가 망하는 날까지 해보겠습니다.

10으로 나는 나머지가 0이 되는 회차이므로
현재 스타벅스에서 프로모션 음료로 판매 하는 슈크림 라뗴를 스페셜 프로모션 음료로 준비해봤습니다.

이번 모임 참석을 포함해서 4회 참석을 달성하시면 음료가 업그레이드 됩니다!

<img width="867" alt="image" src="https://user-images.githubusercontent.com/17442457/158058728-12eb5577-e252-468e-accc-81330885f378.png">

**Comment by jongfeel** [comment]
## [오브젝트](http://aladin.kr/p/kLQlP) 읽고 정리하기

- https://github.com/jongfeel/objects/issues/23

**Comment by chichoon** [comment]
필라테스 신청 서버가 터져서 계속 토요일 아침에 잡는 바람에 ㅡ,,ㅡ; 오랜만에 돌아왔습니다

# 오늘 할 일
- 백트래킹 정리하기
- 알고리즘 1 ~ 2문제 풀기

**Comment by exgs** [comment]
오랜만에 왔습니다, 1시쯤에 약속이 있는지라, 11시 반 ~12시까지만 진행 할께요
# 할 일
유니티 그래픽스 최적화 스타트업 - 오지헌

**Comment by soo-bak** [comment]
### 목표
- [ ] LIS 문제 해결 방법 중 시간 복잡도 `O(n log n)` 알고리즘 공부 후 노션 정리
- [ ] [관련 문제](https://www.acmicpc.net/problem/14003) 풀이
---
### 결과
- 추후 수정 예정

**Comment by seoyoungit** [comment]
# 목표

- access network 노션 정리하며 공부 (공부 자료 : 컴퓨터네트워킹 하향식 접근)

# 결과 
[노션 정리 page](https://sordid-brisket-35e.notion.site/network-edge-513531a1f40d46059df9b750cfc245ec)

**Comment by JSY8869** [comment]
## 목표
leetcode 문제 풀기
- Graph - [1192. Critical Connections in a Network](https://leetcode.com/problems/critical-connections-in-a-network/)
- DFS/BFS - [2092. Find All People With Secret](https://leetcode.com/problems/find-all-people-with-secret/)
## 시간이 남으면
- 자바의 정석 7.9 디폴트 메서드와 static메서드 파트 읽고 노션에 정리하기

**Comment by jongfeel** [comment]
@JSY8869 
슈크림 라떼 프로모션 기간이 끝나 이번 프로모션 음료로 딸기 드림 말차 라떼로 드리도록 하겠습니다.
