### ISSUE TITLE
80th online meetup, 2022-05-28 with special promotion: `Lavender Blonde Starbucks Double Shot`

### ISSUE THREAD

**Issue by jongfeel** [ThinkAboutSoftware/OnlineSelfCodingGroup#130]
https://meet.google.com/jyx-mxnq-kpk

### 참여 방법:

Assignees에 자신의 github 계정을 self로 추가
2시간 분량의 할 내용에 대해 댓글 작성 (최소 모임 시작 전까지)
빛의 속도 혹은 (주말, 휴일 포함) 최소 3일 내에 구글 캘린더 등록 메일 확인
모임 시간에 각자 개발 관련된 공부 진행

- 시작: 10시 30분
- 할 것 이야기: 5분 ~ 10분 간 진행
- 진행: 2시간, 하지만 쉬는 시간 및 기타 잡일 감안해서 1시간 ~ 1시간 30분 정도로 진행
- 한 것 이야기: 최대한 12시 40분까지, 조금 오버할 수 있음 (오래 하면 30분 얘기하기도 함)

모임 끝난 후 공부한 내용 정리 & 링크 추가 => 최소 다음 모각코 전까지 확인 가능해야 함.

**주의: 회사일 혹은 마감 기한 임박한 일 처리의 경우는 최대한 자제해 주세요. 주말 아침에 일하면 우울하니까요. ㅜㅜ**

---

어느덧 80회 입니다. 
70에서 79회차 까지 망했던 회차가 없어서 다행이라고 생각합니다.
역시 이번에도 10으로 나눈 나머지가 0이 되는 회차이므로
스타벅스에서 새로 나온 음료인 라벤더 블론드 스타벅스 더블 샷 음료로 준비해봤습니다.

이번 모임 참석을 포함해서 4회 참석을 달성하시면 음료가 업그레이드 됩니다!

![image](https://user-images.githubusercontent.com/17442457/169654223-5aa8f258-e9bd-42fc-b9bf-120ea18d84e1.png)

**Comment by jongfeel** [comment]
## [오브젝트](http://aladin.kr/p/kLQlP) 읽고 정리하기

- https://github.com/jongfeel/objects/issues/57

---

이날은 42서울 멘토단 워크샵 일정이 있습니다.
부산 라발스 호텔입니다.
[작년처럼](https://github.com/ThinkAboutSoftware/OnlineSelfCodingGroup/issues/92) 오전에도 일정이 있을 것 같아 책만 읽고 정리는 나중에 해볼 예정입니다.

**Comment by exgs** [comment]
### 할 일
알고리즘 문제 풀기(Java, Python)
새로운 언어로 풀기때문에 난이도 매우 낮은 문제로 다다익선으로 접근할 예정입니다.

**Comment by chichoon** [comment]
# 오늘 할 일
여느때처럼 알고리즘 2문제 정도 풀겠습니다
