### ISSUE TITLE
90th onilne meetup, 2022-08-06 with special promotion: Mugwort Cream Frappuccino with Cold Brew

### ISSUE THREAD

**Issue by jongfeel** [ThinkAboutSoftware/OnlineSelfCodingGroup#149]
https://meet.google.com/jyx-mxnq-kpk

### 참여 방법:

Assignees에 자신의 github 계정을 self로 추가
2시간 분량의 할 내용에 대해 댓글 작성 (최소 모임 시작 전까지)
빛의 속도 혹은 (주말, 휴일 포함) 최소 3일 내에 구글 캘린더 등록 메일 확인
모임 시간에 각자 개발 관련된 공부 진행

- 시작: 10시 30분
- 할 것 이야기: 5분 ~ 10분 간 진행
- 진행: 2시간, 하지만 쉬는 시간 및 기타 잡일 감안해서 1시간 ~ 1시간 30분 정도로 진행
- 한 것 이야기: 최대한 12시 40분까지, 조금 오버할 수 있음 (오래 하면 30분 얘기하기도 함)

모임 끝난 후 공부한 내용 정리 & 링크 추가 => 최소 다음 모각코 전까지 확인 가능해야 함.

**주의: 회사일 혹은 마감 기한 임박한 일 처리의 경우는 최대한 자제해 주세요. 주말 아침에 일하면 우울하니까요. ㅜㅜ**

---

### Special promotion

90회차에 왔습니다. 이제는 습관처럼 하게 되는 긍정적효과가 있는 것 같습니다.
90회는 프로모션 음료인 `우리 쑥 크림 프라푸치노 with 콜드 브루` 입니다.
프로모션 기간이 지나서 해당 음료를 못구하거나 취향이 다르면
가격대가 같은 다른 음료로 드셔도 좋습니다.

![90](https://image.istarbucks.co.kr/upload/store/skuimg/2022/07/%5B9200000003816%5D_20220701141004539.jpg)

**Comment by chichoon** [comment]
# 할 일

저번 회차 기프티콘 잘 받았습니다 ㅎ 카카오톡으로 메시지를 보내는 게 실례가 될까 싶어 메시지를 못 드렸네요
감사인사 남기고 갑니다 m(_ _)m 꾸벅

오늘도 블로그에 글 1개 이상 작성해보려구 합니당 주제는 아직 미정이지만 정규표현식 관련 글을 마저 적거나 OSI 7계층에서 5~7단계를 마저 마무리해볼까 싶습니다

**Comment by fkdl0048** [comment]
감사합니다..! 덕분에 무료로 스타벅스에서 카공이라는걸 해볼 수 있을 것 같습니다..!

모각코를 하면서 느낀점이지만 한주가 정말 빨리 지나가는 것 같습니다..한게 별로 없는데..
---
마찬가지로 게임수학을 계속 할것 같습니다..!

**Comment by jongfeel** [comment]
## [오브젝트](http://aladin.kr/p/kLQlP) 읽고 정리하기

- https://github.com/jongfeel/objects/issues/72

**Comment by aquamagic9** [comment]
안녕하세요! 이번에 처음 참여해보는 조현우 입니다~

저는 이번시간에 모두의 네트워크 3장~6장 공부 및 노션 정리 할 예정입니다..!
