### ISSUE TITLE
Youtube PlayList

### ISSUE THREAD

**Issue by fora22** [ThinkAboutSoftware/OnlineSelfCodingGroup#16]
음악 취향 ~강요~ 공유를 위해 한 번 알아보았다. #10 

Youtube PlayList는 한 계정의 플레이리스트에 허락된 공동 사용자가 동영상을 추가할 수 있게 되어 있다. 

따라서 글작성의 편의를 위해 플레이리스트를 가지고 있는 계정은 **제공자**라고 하고 공동작업자(플레이리스트를 추가하는 사람)를 **이용자**라고 하겠다.
- 물론 제공자도 동영상을 추가할 수 있다.
- Chrome 환경에서 실험했다는 것을 참고하기 바람.
- 문서 정리하듯이 써서 존칭으로 써져 있지 않은 것은 양해 바랍니다.

# 방법
## 제공자
1. 제공자는 구글 계정에 로그인한 상태에서 [유튜브 스튜디오](https://studio.youtube.com/)로 접속한다.
2. 로그인이 되어있다면 제공자 계정의 채널 대시보드가 열릴테고 왼쪽 '메뉴'의 '**재생목록**'을 선택한다.
3. 제공자 계정의 재생목록이 있을텐데 오른쪽 위의 '새 재생목록'을 누른다. 
    - 공개 상태는 '공개'로 한다(비공개만 아니면 상관 없긴 하다).
    - 기존 재생목록을 사용해도 상관 없다.    
4. 만든 재생목록을 클릭하고, 재생목록 제목 아래의 '더보기' ...을 클릭한다.
      ![image](https://user-images.githubusercontent.com/48875566/103150256-b1a58700-47b5-11eb-8fd3-a9c96f25a36c.png)
5. '**공동작업**'을 클릭한다.
6. '공동작업자가 재생목록에 동영상을 추가할 수 있음'을 누르고 완료를 누른다.
7. 다시 '**공동작업**'을 클릭하면 이용자(공동작업자)에게 보낼 링크가 있다.
8. 그 링크를 이용자들에게 공유해준다.

## 이용자
1. 구글 계정에 로그인한다.
2. 이용자는 제공자에게 받은 링크를 클릭하면 오른쪽 위에 `계속` 버튼이 생긴 것을 알 수 있다. `계속` 버튼을 클릭한다.
3. 클릭 후 재생목록 제목 아래의 보관함 저장을 클릭한다.
4. 이용자 계정의 '보관함' 가보면 제공자가 만든 재생목록이 추가되있음을 알 수 있다.
5. 이제 원하는 동영상에가서 동영상 밑의 `저장` 버튼을 누르면 제공자와 연결된 재생목록이 뜬다. 그 곳을 체크하여 저장한다.
      ![image](https://user-images.githubusercontent.com/48875566/103150295-13fe8780-47b6-11eb-8850-dc93e034a055.png)

# Reference
[재생목록 공동작업 - Youtube 고객센터](https://support.google.com/youtube/answer/6109639?hl=ko)

**Comment by jongfeel** [comment]
좋은 공유 글 감사합니다.

사실 유튜브가 알려준 방법대로 재생목록을 추가하고 공동 작업자를 넣었는데 잘 안되는거 같아서 그랬습니다.

https://www.youtube.com/playlist?list=PLBFc2T4S7JnvZrV92zSlOfqeYHj7-qJfB&jct=hkFSXgrr2X-4yldTm5iMtpqnGcjKRQ

@fora22 
요 링크로 다시 해보시고 동영상이 추가되는지 확인해 주세요.

만약 잘 되면 이걸 가지고 재생목록을 관리해 보도록 하겠습니다.

**Comment by jongfeel** [comment]
@fora22 
성공 하셨군요.

제가 넣어뒀던 3곡 중에 한곡이 삭제되어 있는데, 테스트 하느라 삭제하신 거겠죠?
제가 다시 추가해 뒀습니다. (Suede - Beautiful Ones)

이제 되는거 같으니 공지를 수정해 보겠습니다.

**Comment by fora22** [comment]
삭제한 기억은 없는데... 삭제가 되었다니 죄송합니다 ㅠㅠ

이번 주 모각코가 기대가 되네요 ㅎㅎ

**Comment by jongfeel** [comment]
자유롭게 곡 추가 가능
다양항 취향 공유를 위해 가장 적게 곡 추가를 한 사람보다 +1 곡 이상 추가 금지
