### ISSUE TITLE
100th online meetup, 2022-10-15, with special dessert set

### ISSUE THREAD

**Issue by jongfeel** [ThinkAboutSoftware/OnlineSelfCodingGroup#169]
안녕하세요.

2020년 11월 14일 첫 온라인 모각코를 진행한 이후
연중 무휴로 100 번을 진행하였습니다.

저 혼자만의 의지일 수도 있겠지만
토요일 오전 주말에 공부한다는 다른 모든 분들의 의지로 여기까지 오게 된 거라 믿고 싶습니다.

그래서 이번 회차에는 `부드러운 디저트 세트`를 준비했습니다.
이번 회차 **포함** 스탬프 4장을 획득하신 분에게 
`부드러운 디저트 세트` 스타벅스 e-gift item을 전달드리겠습니다.

![1000341407900_i1_1200](https://user-images.githubusercontent.com/17442457/194974079-b356ecb7-5ddc-4b3a-9e79-fae4ca25c5ac.png)

---

https://meet.google.com/jyx-mxnq-kpk

### 참여 방법:

Assignees에 자신의 github 계정을 self로 추가
2시간 분량의 할 내용에 대해 댓글 작성 (최소 모임 시작 전까지)
빛의 속도 혹은 (주말, 휴일 포함) 최소 3일 내에 구글 캘린더 등록 메일 확인
모임 시간에 각자 개발 관련된 공부 진행

- 시작: 10시 30분
- 할 것 이야기: 5분 ~ 10분 간 진행
- 진행: 2시간, 하지만 쉬는 시간 및 기타 잡일 감안해서 1시간 ~ 1시간 30분 정도로 진행
- 한 것 이야기: 최대한 12시 40분까지, 조금 오버할 수 있음 (오래 하면 30분 얘기하기도 함)

모임 끝난 후 공부한 내용 정리 & 링크 추가 => 최소 다음 모각코 전까지 확인 가능해야 함.

**주의: 회사일 혹은 마감 기한 임박한 일 처리의 경우는 최대한 자제해 주세요. 주말 아침에 일하면 우울하니까요. ㅜㅜ**

**Comment by chichoon** [comment]
# 할 일

영광의 100번째 모각코 제가 한번 참여해보겠습니다
블로그에 게시글 적기 (Socket 통신!!!!)

**Comment by eunyeong-so** [comment]
100번 째 모각코!!!!! ✨🎉 다들 멋지십니당

**Comment by ellen310** [comment]
# 컴퓨터 그래픽스

- [ ] 3장 모델링 수강
- [ ] 1-3장 요약 정리

오랜만에 참여하는데 마침 100회네요!!! 영광입니다😄🎉

**Comment by wjrmffldrhrl** [comment]
# 개인 프로젝트
## Hotdeal Next

**Comment by jongfeel** [comment]
## [오브젝트](http://aladin.kr/p/kLQlP) 읽고 정리하기

- https://github.com/jongfeel/objects/issues/84

---

오늘은 호텔에 있고 출국 준비를 해야 해서
내용만 읽고 정리는 나중에 하게 될 것 같습니다.

**Comment by exgs** [comment]
### 미처 참여는 못했지만, 모각코의 100회를 축하합니다..! ㊗️
