### ISSUE TITLE
109th online meetup, 2022-12-17 with home coming day 2022

### ISSUE THREAD

**Issue by jongfeel** [ThinkAboutSoftware/OnlineSelfCodingGroup#189]
https://meet.google.com/jyx-mxnq-kpk

### 참여 방법:

Assignees에 자신의 github 계정을 self로 추가
약 1시간 30분 분량의 할 내용에 대해 댓글 작성 (최소 모임 시작 전까지)
빛의 속도 혹은 (주말, 휴일 포함) 최소 3일 내에 구글 캘린더 등록 메일 확인
모임 시간에 각자 개발 관련된 공부 진행

- 시작: 10시 30분
- 할 것 이야기: 5분 ~ 10분 간 진행
- 진행: 2시간, 하지만 쉬는 시간 및 기타 잡일 감안해서 1시간 ~ 1시간 30분 정도로 진행
- 한 것 이야기: 최대한 12시 40분까지, 조금 오버할 수 있음 (오래 하면 30분 얘기하기도 함)

모임 끝난 후 공부한 내용 정리 & 링크 추가 => 최소 다음 모각코 전까지 확인 가능해야 함.

**주의: 회사일 혹은 마감 기한 임박한 일 처리의 경우는 최대한 자제해 주세요. 주말 아침에 일하면 우울하니까요. ㅜㅜ**

---

이날은 home coming day 2022가 열리는 날입니다.
오후 3시에서 오후 6시 20분 까지, 까페 까사꼬모다에서 열립니다.
https://github.com/ThinkAboutSoftware/HomeComingDay

**Comment by chichoon** [comment]
# 할 일

홈커밍데이 매우 기대됩니다 호호호
항상 그랬듯 블로그에 글 1개 정리하기 를 목표로 해보겠습니다

**Comment by wisdom08** [comment]
### TODO 
- 댓글 기능 구현한 거 설계 방식 고민해서 변경해보기

**Comment by yeslee-v** [comment]
# 할 일

- [yarn berry 글](https://toss.tech/article/node-modules-and-yarn-berry) 읽어보기
- [graphQL 강의](https://nomadcoders.co/graphql-for-beginners/lobby) 보기: ~ 3(시간 되면 ~ 4)

**Comment by jongfeel** [comment]
## [클린 코드 Clean Code - 애자일 소프트웨어 장인 정신](http://aladin.kr/p/cGVOm) 읽고 정리하기

- https://github.com/jongfeel/BookReview/issues/285

---

![image](https://user-images.githubusercontent.com/17442457/208217426-5fed74db-67fb-4276-a0fd-de637796a9a3.png)

지금은 스타벅스에 있고 
오후 12시 30분 결혼식 (혜화역 근처입니다)
오후 2시 40분 쯤 까페 까사꼬모다 방문 예정입니다.
