### ISSUE TITLE
110th online meetup, 2022-12-24 with special promotion: Toffee Nut Latte

### ISSUE THREAD

**Issue by jongfeel** [ThinkAboutSoftware/OnlineSelfCodingGroup#191]
https://meet.google.com/jyx-mxnq-kpk

### 참여 방법:

Assignees에 자신의 github 계정을 self로 추가
약 1시간 30분 분량의 할 내용에 대해 댓글 작성 (최소 모임 시작 전까지)
빛의 속도 혹은 (주말, 휴일 포함) 최소 3일 내에 구글 캘린더 등록 메일 확인
모임 시간에 각자 개발 관련된 공부 진행

- 시작: 10시 30분
- 할 것 이야기: 5분 ~ 10분 간 진행
- 진행: 2시간, 하지만 쉬는 시간 및 기타 잡일 감안해서 1시간 ~ 1시간 30분 정도로 진행
- 한 것 이야기: 최대한 12시 40분까지, 조금 오버할 수 있음 (오래 하면 30분 얘기하기도 함)

모임 끝난 후 공부한 내용 정리 & 링크 추가 => 최소 다음 모각코 전까지 확인 가능해야 함.

**주의: 회사일 혹은 마감 기한 임박한 일 처리의 경우는 최대한 자제해 주세요. 주말 아침에 일하면 우울하니까요. ㅜㅜ**

---

110회 모임입니다.
이번 모임 포함 스탬프 4개 획득하시면
스타벅스 토피 넛 라떼를 드리겠습니다.
토피 넛 라떼 시즌이 끝난다고 해도 해당 시점에 프로모션 음료로 대체해서 드리도록 하겠습니다.

![image](https://user-images.githubusercontent.com/17442457/208278603-3ba5dff4-9fb9-4eff-8cc0-00bdeda2faed.png)

**Comment by chichoon** [comment]
# 할 일

블로그에 글 1개 적기!!!!!

홈커밍데이 이후로 갑자기 의욕이 샘솟습니다
아자아자화이팅

**Comment by yeslee-v** [comment]
# 할 일
2022 회고록 적기

**Comment by jongfeel** [comment]
## [코틀린 마이크로서비스 개발](http://aladin.kr/p/r2BY6) 읽고 정리하기

- https://github.com/jongfeel/BookReview/issues/275

---

우선 책을 먼저 읽고
정리는 나중에 진행할 예정입니다

**Comment by ohdair** [comment]
# 할 일
객체지향의 사실과 오해 독서
