### ISSUE TITLE
1st online meetup, 2020-11-14

### ISSUE THREAD

**Issue by yoonucho** [ThinkAboutSoftware/OnlineSelfCodingGroup#2]
10:00 - 12:00 진행 예정

**Comment by jongfeel** [comment]
엇 윤우님
#1 
요기 issue에 assignees에 추가만 해주시면 되고요
모각코때 할 내용이 지금(?) 있으시면 코멘트를 달아 주시면 됩니다. 14일 오전 10시 전까지 코멘트 달아주시면 됩니다.

**Comment by yoonucho** [comment]
> 엇 윤우님
> #1
> 요기 issue에 assignees에 추가만 해주시면 되고요
> 모각코때 할 내용이 지금(?) 있으시면 코멘트를 달아 주시면 됩니다. 14일 오전 10시 전까지 코멘트 달아주시면 됩니다.

앗 ㅋㅋ 제가 멘토님 글에 assignees 추가하려고 했는데 잘 안되더라고요 우선 이 이슈는 닫고 해결해보겠습니다!

**Comment by jongfeel** [comment]
제가 
Settings > Manage access에 
제 Community team 멤버 모두를 Triage 권한을 추가 했습니다.

다시 해보시고 안되면 알려주세요.

**Comment by yoonucho** [comment]
넵 알겠습니다!

**Comment by yoonucho** [comment]
제가 저를 추가했더니 멘토님이 사라져서 멘토님을 다시 추가했습니다 ㅠㅠ
