### ISSUE TITLE
120th online meetup, 2023-03-04 with special promotion: Iced Brown Sugar Oat Shaken Espresso

### ISSUE THREAD

**Issue by jongfeel** [ThinkAboutSoftware/OnlineSelfCodingGroup#211]
### 참여 방법

토요일 오전 10시 30분에 아래 google meet 링크를 통해 접속
https://meet.google.com/jyx-mxnq-kpk

해당 이슈 글의 assignees에 자신의 github 계정을 self로 추가
약 1시간 30분 분량의 할 내용에 대해 댓글 작성 (최소 모임 시작 전까지)
구글 캘린더 일정 등록 메일 확인을 통해서도 가능 (일정 관리에 도움도 드립니다)
모임 시간에 각자 개발 관련된 공부 진행

- 시작: 10시 30분
- 할 것 이야기: 5분 ~ 10분 간 진행
- 진행: 2시간, 하지만 쉬는 시간 및 기타 잡일 감안해서 1시간 30분 정도로 진행
- 한 것 이야기: 최대한 12시 40분까지, 조금 오버할 수 있음 (오래 하면 30분 얘기하기도 함)

모임 끝난 후 공부한 내용 정리 & 링크 추가 => 최소 다음 모각코 전까지 확인 가능해야 함.

**주의: 회사일 혹은 마감 기한 임박한 일 처리의 경우는 최대한 자제해 주세요. 주말 아침에 일하면 우울하니까요. ㅜㅜ**

---

120회 모임입니다.
이번 모임 포함 스탬프 4개 획득하시면
브라운 슈가 오트 쉐이큰 에스프레소 시즌 음료로 변경됩니다.
시즌이 끝나면 음료를 받는 시점의 프로모션 음료로 대체해서 드리도록 하겠습니다.

![image](https://user-images.githubusercontent.com/17442457/221388571-15c77244-70ef-4841-9926-528bfe134bce.png)

**Comment by fkdl0048** [comment]
- https://github.com/fkdl0048/BookReview/issues/38  

벌써 120회라니..!

**Comment by ohdair** [comment]
리팩터링 독서
- [ ] 5장 카탈로그 보는 법

**Comment by chichoon** [comment]
흑당오트쉐이크에스프레소 (?) 맛있더라구욤

# 할 일

42의 모든 과제가 마무리되어 가고 있습니다...
이제 리팩토링을 읽으며 정리를 천천히 해 보려구 합니다...

**Comment by hyunhyee** [comment]
할일
- [ ] 템플릿 메서드 패턴 정리
- [ ] 컴포지트 패턴 정리
- [ ] 재귀 알고리즘 연습문제 정리

**Comment by jongfeel** [comment]
## [코틀린 마이크로서비스 개발](http://aladin.kr/p/r2BY6) 읽고 정리하기

- https://github.com/jongfeel/BookReview/issues/344
