### ISSUE TITLE
130th online meetup, 2023-05-13, special promotion: Mango Dragonfruit with Lemonade Starbucks Refreshers

### ISSUE THREAD

**Issue by jongfeel** [ThinkAboutSoftware/OnlineSelfCodingGroup#232]
### 참여 방법

토요일 오전 10시 30분에 아래 google meet 링크를 통해 접속
https://meet.google.com/jyx-mxnq-kpk

이 이슈 글의 assignees에 자신의 github 계정을 self로 추가
약 1시간 30분 분량의 할 내용에 대해 댓글 작성 (최소 모임 시작 전까지)
구글 캘린더 일정 등록 메일 확인을 통해서도 가능 (일정 관리에 도움도 드립니다)
모임 시간에 각자 개발 관련된 공부 진행

- 시작: 10시 30분, 각자 오늘 진행할 것 이야기 5분 ~ 10분 간 진행
  - 자기소개: 새로 오신 분이 있으면 각자 짧은 자기소개가 진행됩니다
- 진행: 2시간, 하지만 쉬는 시간 및 기타 잡일 감안해서 1시간 30분 정도로 진행
- 완료: 12시 30분, 이후 각자 진행한 것 이야기, 12시 40분 전후로 종료.

모임 끝난 후 공부한 내용 정리 & 링크 추가 => 최소 다음 모각코 전까지 확인 가능해야 함.

**주의: 회사일 혹은 마감 기한 임박한 일 처리의 경우는 최대한 자제해 주세요. 주말 아침에 일하면 우울하니까요. ㅜㅜ**

---

어느덧 130회차까지 왔습니다.
이번 모임 포함 스탬프 4개 획득하시면
망고 용과 레모네이드 스타벅스 리프레셔 시즌 음료로 변경됩니다.
시즌이 끝나면 음료를 받는 시점의 프로모션 음료로 대체해서 드리도록 하겠습니다.

![Mango Dragonfruit with Lemonade Starbucks Refreshers](https://user-images.githubusercontent.com/17442457/236654163-5dcb39dc-9091-4aaa-a723-4d0c67d2991f.jpg)

**Comment by fkdl0048** [comment]
시간에 맞게 참가 하고 책은 이동중에 읽을 것 같습니다..

- https://github.com/fkdl0048/BookReview/issues/68

**Comment by chichoon** [comment]
용과 리프레셔 되게 맛있다고 하더라구요

# 할 일

[Next.js 라우터 적다 만 것 마저 적기](https://chichoon.notion.site/App-Pages-0800d2150ed84860a5ec351994d5ba33)

**Comment by TaeHyoungKwon** [comment]
10분정도 늦을것같습니다 들어와서 바로시작 하겠습니다

**Comment by jongfeel** [comment]
## [코틀린 마이크로서비스 개발](http://aladin.kr/p/r2BY6) 읽고 정리하기

- https://github.com/jongfeel/BookReview/issues/433
