### ISSUE TITLE
150th online meetup, 2023-09-30 with special promotion: Banana Caramel Cream Frappuccino

### ISSUE THREAD

**Issue by jongfeel** [ThinkAboutSoftware/OnlineSelfCodingGroup#272]
### 참여 방법

토요일 오전 10시 30분에 아래 google meet 링크를 통해 접속
https://meet.google.com/jyx-mxnq-kpk

이 이슈 assignees에 자신의 github 계정을 추가
약 1시간 30분 분량의 할 내용에 대해 댓글 작성 (최소 모임 시작 전까지)
구글 캘린더 일정 등록 메일 확인을 통해서도 가능 (일정 관리에 도움도 드립니다)
모임 시간에 각자 개발 관련된 공부 진행

- 시작: 10시 30분, 각자 오늘 진행할 것 이야기 5분 ~ 10분 간 진행
  - 자기소개: 새로 오신 분이 있으면 각자 짧은 자기소개가 진행됩니다
- 진행: 2시간, 하지만 쉬는 시간 및 기타 잡일 감안해서 1시간 30분 정도로 진행
- 완료: 12시 30분, 이후 각자 진행한 것 이야기, 12시 40분 전후로 종료.

모임 끝난 후 공부한 내용 정리 & 링크 추가 => 최소 다음 모각코 전까지 확인 가능해야 함.

**주의: 회사일 혹은 마감 기한 임박한 일 처리의 경우는 최대한 자제해 주세요. 주말 아침에 일하면 우울하니까요. ㅜㅜ**

---

업데이트가 늦었습니다.
이번 150회차 포함 스탬프 4장을 모으신 분들은 바나나 카라멜 크림 프라푸치노로 변경해서 드릴 예정입니다.
프로모션 기간이 끝난 이후에도 6.3천원과 동일한 음료를 드실 수 있습니다.
물론 추석 다음날 주말의 시작이라 지방으로 이동하시는 분이나 쉬고 싶은 분들에게는 어려울 수 있지만
참석하실 수 있는 분들은 자유롭게 참석 하면 좋겠습니다.

![image](https://github.com/ThinkAboutSoftware/OnlineSelfCodingGroup/assets/17442457/d6706309-a0d5-4644-8918-bba4deb2733c)

**Comment by fkdl0048** [comment]
- https://github.com/fkdl0048/BookReview/issues/145

**Comment by chichoon** [comment]
# 할 일

함수형 코딩 5장 (챕터 5) 읽기

**Comment by cyhcyh100** [comment]
Lua 스크립트 스터디

**Comment by momoci99** [comment]
# 할일

이펙티브 타입스크립트 2장 스터디
- 챕터 16
- 챕터 17

**Comment by JSY8869** [comment]
프로그래머의 길 멘토에게 묻다
4장 읽고 [노션](https://www.notion.so/37522e4be04946fbb3c87287159c3ca6?pvs=4)에 정리하기

**Comment by Arat5724** [comment]
![image](https://github.com/ThinkAboutSoftware/OnlineSelfCodingGroup/assets/79699284/f8a2a127-add3-4a39-b5c6-b9e84b07e001)

css 수정하기

+ 시간 남으면 개봉 애니메이션 생각해보기

**Comment by jongfeel** [comment]
## [코틀린 마이크로서비스 개발](http://aladin.kr/p/r2BY6) 읽고 실습 해보고 정리하기

- https://github.com/jongfeel/BookReview/issues/563
  - 책 내용에서 redhat openshift 설정에 어려움이 있어서 오래 걸리면 건너 뛸 예정입니다

**Comment by chichoon** [comment]
모기때문에 잠을 한 숨도 못자서,.. 11시 반까지 자다가 들어가는 것에 실패했습니다 ㅠㅠ 다음시간에 뵙겠습니다..
