### ISSUE TITLE
160th online meetup 2023-12-09 with special promotion: Toffee nut latte

### ISSUE THREAD

**Issue by jongfeel** [ThinkAboutSoftware/OnlineSelfCodingGroup#293]
### 참여 방법

토요일 오전 10시 30분에 아래 google meet 링크를 통해 접속
https://meet.google.com/jyx-mxnq-kpk

이 이슈 assignees에 자신의 github 계정을 추가
약 1시간 30분 분량의 할 내용에 대해 댓글 작성 (최소 모임 시작 전까지)
구글 캘린더 일정 등록 메일 확인을 통해서도 가능 (일정 관리에 도움도 드립니다)
모임 시간에 각자 개발 관련된 공부 진행

- 시작: 10시 30분, 각자 오늘 진행할 것 이야기 5분 ~ 10분 간 진행
  - 자기소개: 새로 오신 분이 있으면 각자 짧은 자기소개가 진행됩니다
- 진행: 2시간, 하지만 쉬는 시간 및 기타 잡일 감안해서 1시간 30분 정도로 진행
- 완료: 12시 30분, 이후 각자 진행한 것 이야기, 12시 40분 전후로 종료.

모임 끝난 후 공부한 내용 정리 & 링크 추가 => 최소 다음 모각코 전까지 확인 가능해야 함.

**주의: 회사일 혹은 마감 기한 임박한 일 처리의 경우는 최대한 자제해 주세요. 주말 아침에 일하면 우울하니까요. ㅜㅜ**

---

어느덧 160회가 되었습니다.
이번 회차 포함해서 스탬프 4개가 되면 토피 넛 라떼를 드리려고 합니다.
계속해서 부지런히 참석해 주신 분들에게 감사 드립니다.

![image](https://github.com/ThinkAboutSoftware/OnlineSelfCodingGroup/assets/17442457/c5acfd5a-19c1-44e2-a5b3-5b90b32c2d63)

**Comment by fkdl0048** [comment]
- https://github.com/fkdl0048/BookReview/issues/183

**Comment by jongfeel** [comment]
> * ~[2장 함께 fkdl0048/BookReview#183](https://github.com/fkdl0048/BookReview/issues/183)~
> * ~[3장 애자일 fkdl0048/BookReview#184](https://github.com/fkdl0048/BookReview/issues/184)~
> 
> 주중에 책을 다 읽어서 아마 주말에는 모각코때는 시험 공부를 할 것 같은데,, 가능할까요?

책을 미리 읽었다면, 예외 케이스로 하셔도 될 것 같습니다.

**Comment by chichoon** [comment]
# 할 일

함수형 코딩 책 읽기 (17챕터)

홈커밍데이 회신 후 생각났는데, 올해 발표는 힘들 것 같습니다 😿 준비 기간이 촉박하네요 ,,

**Comment by momoci99** [comment]
# 할일
키 이벤트 바인딩 관련 내용 정리 + @

**Comment by nonoaa** [comment]
# 할 일
클린 아키텍처 15, 16장 읽기

**Comment by jongfeel** [comment]
## [도메인 주도 설계](http://aladin.kr/p/p6ehn) 읽고 정리하기

- https://github.com/jongfeel/BookReview/issues/606

에서 ENTITY와 VALUE OBJECT 부분 읽고 정리
