### ISSUE TITLE
161th online meetup, 2023-12-16 with Home coming day 2023

### ISSUE THREAD

**Issue by jongfeel** [ThinkAboutSoftware/OnlineSelfCodingGroup#295]
### 참여 방법

토요일 오전 10시 30분에 아래 google meet 링크를 통해 접속
https://meet.google.com/jyx-mxnq-kpk

이 이슈 assignees에 자신의 github 계정을 추가
약 1시간 30분 분량의 할 내용에 대해 댓글 작성 (최소 모임 시작 전까지)
구글 캘린더 일정 등록 메일 확인을 통해서도 가능 (일정 관리에 도움도 드립니다)
모임 시간에 각자 개발 관련된 공부 진행

- 시작: 10시 30분, 각자 오늘 진행할 것 이야기 5분 ~ 10분 간 진행
  - 자기소개: 새로 오신 분이 있으면 각자 짧은 자기소개가 진행됩니다
- 진행: 2시간, 하지만 쉬는 시간 및 기타 잡일 감안해서 1시간 30분 정도로 진행
- 완료: 12시 30분, 이후 각자 진행한 것 이야기, 12시 40분 전후로 종료.

모임 끝난 후 공부한 내용 정리 & 링크 추가 => 최소 다음 모각코 전까지 확인 가능해야 함.

**주의: 회사일 혹은 마감 기한 임박한 일 처리의 경우는 최대한 자제해 주세요. 주말 아침에 일하면 우울하니까요. ㅜㅜ**

---

이날은 home coming day 2023이 있는 날입니다.
마포에 채그로 북까페 지하 1층에서 오후 1시에 열리는데
여태까지 열정적으로 온라인 모각코를 참여하시는 분들이 거의 참여하시는 걸로 알고 있습니다.
그래서 온라인 모각코를 참여하면서 home coming day 2023에 참여하기가 쉽지 않을 것이라 생각합니다.

저는 오전 10시 30분에 채그로 북까페 8층에 있는 까페에서 진행할 예정인데
혹시나 일찍 오셔서 온라인 모각코도 참여하실 수 있는 분이 있으면
제가 커피와 샌드위치를 사드리려고 합니다.
물론 온라인으로 하기 때문에 home coming day에 참여 못해도 온라인 모각코는 참여할 수 있습니다.

**Comment by yeslee-v** [comment]
[백엔드 개발생산성 향상을 위한 Debugger 활용법](https://www.hanbitn.com/product/msa2023-debugger/) 강의 듣고 요약하기

**Comment by jongfeel** [comment]
저는 채그로 북까페 8층에 와 있습니다.

저는 home coming day 2023때 얘기할 내용에 대해 정리하는 시간을 가져보려고 합니다.

![image](https://github.com/ThinkAboutSoftware/OnlineSelfCodingGroup/assets/17442457/607c3151-faa4-4539-bb09-45d3b2e07615)

![image](https://github.com/ThinkAboutSoftware/OnlineSelfCodingGroup/assets/17442457/c5e97ea6-c877-4181-9ff2-6af9ba5526f5)
