### ISSUE TITLE
170th online meetup, 2024-02-17 with special promotion: White taro latte

### ISSUE THREAD

**Issue by jongfeel** [ThinkAboutSoftware/OnlineSelfCodingGroup#313]
### 참여 방법

토요일 오전 10시 30분에 아래 google meet 링크를 통해 접속
https://meet.google.com/jyx-mxnq-kpk

이 이슈 assignees에 자신의 github 계정을 추가
약 1시간 30분 분량의 할 내용에 대해 댓글 작성 (최소 모임 시작 전까지)
구글 캘린더 일정 등록 메일 확인을 통해서도 가능 (일정 관리에 도움도 드립니다)
모임 시간에 각자 개발 관련된 공부 진행

- 시작: 10시 30분, 각자 오늘 진행할 것 이야기 5분 ~ 10분 간 진행
  - 자기소개: 새로 오신 분이 있으면 각자 짧은 자기소개가 진행됩니다
- 진행: 2시간, 하지만 쉬는 시간 및 기타 잡일 감안해서 1시간 30분 정도로 진행
- 완료: 12시 30분, 이후 각자 진행한 것 이야기, 12시 40분 전후로 종료.

모임 끝난 후 공부한 내용 정리 & 링크 추가 => 최소 다음 모각코 전까지 확인 가능해야 함.

**주의: 회사일 혹은 마감 기한 임박한 일 처리의 경우는 최대한 자제해 주세요. 주말 아침에 일하면 우울하니까요. ㅜㅜ**

---

170회차 포함 스탬프가 달성되면 스타벅스 화이트 라로 라떼를 드립니다.
부지런히 참석해 주시는 분들에게 감사 드립니다.

![image](https://github.com/ThinkAboutSoftware/OnlineSelfCodingGroup/assets/17442457/309d1e7a-ec09-4027-8ef0-d8a05ba9d8f0)

**Comment by fkdl0048** [comment]
- https://github.com/fkdl0048/BookReview/issues/180

**Comment by yeslee-v** [comment]
# To Do

- 라즈베리파이 구성품에 대해 알아보기: POCP에서 '훈련이 중요하다'는 문장을 읽고, 현재 제 상황에 비추어보았을 때는 대규모 시스템 설계 책을 읽는 것도 좋지만, 일단 이거 저거 만져보고 시도하는게 더 중요하겠다는 생각이 들더라구요

# Done

**Comment by jeeyn** [comment]
## To do
- 프로그래밍 심리학 11-12장 읽고 정리

## Done
- jeeyn/book-review#21
- jeeyn/book-review#22

**Comment by chichoon** [comment]
# 할 일

알고리즘 2문제 가량 풀기

**Comment by ytw9699** [comment]
# 할 일 
혼자 공부하는 컴퓨터구조 + 운영체제 강의듣기( 섹션 3. 명령어)
https://www.inflearn.com/course/%ED%98%BC%EC%9E%90-%EA%B3%B5%EB%B6%80%ED%95%98%EB%8A%94-%EC%BB%B4%ED%93%A8%ED%84%B0%EA%B5%AC%EC%A1%B0-%EC%9A%B4%EC%98%81%EC%B2%B4%EC%A0%9C/dashboard

**Comment by momoci99** [comment]
# 할 일
e2e 테스트 내용 정리하기

**Comment by jongfeel** [comment]
## [프로그래밍 심리학](http://aladin.kr/p/vGO4E) 읽고 정리하기

- https://github.com/jongfeel/BookReview/issues/643

에서
특수 목적 언어, 범용 언어, 장난감 언어 소단락 정리
질문 정리 및 12장에 보태는 글 정리
