### ISSUE TITLE
200th online meetup, 2024-09-14 with Starbucks Autumn Gift

### ISSUE THREAD

**Issue by jongfeel** [ThinkAboutSoftware/OnlineSelfCodingGroup#375]
### 참여 방법

토요일 오전 10시 30분에 아래 google meet 링크를 통해 접속
https://meet.google.com/jyx-mxnq-kpk

이 이슈 assignees에 자신의 github 계정을 추가
약 1시간 30분 분량의 할 내용에 대해 댓글 작성 (최소 모임 시작 전까지)
구글 캘린더 일정 등록 메일 확인을 통해서도 가능 (일정 관리에 도움도 드립니다)
모임 시간에 각자 개발 관련된 공부 진행

- 시작: 10시 30분, 각자 오늘 진행할 것 이야기 5분 ~ 10분 간 진행
  - 자기소개: 새로 오신 분이 있으면 각자 짧은 자기소개가 진행됩니다
- 진행: 2시간, 하지만 쉬는 시간 및 기타 잡일 감안해서 1시간 30분 정도로 진행
- 완료: 12시 30분, 이후 각자 진행한 것 이야기, 12시 40분 전후로 종료.

모임 끝난 후 공부한 내용 정리 & 링크 추가 => 최소 다음 모각코 전까지 확인 가능해야 함.

**주의: 회사일 혹은 마감 기한 임박한 일 처리의 경우는 최대한 자제해 주세요. 주말 아침에 일하면 우울하니까요. ㅜㅜ**

---

어느덧 온라인 모각코가 200회를 돌파하려고 합니다.
200회 까지 할 줄은 알았지만, 막상 다가오니 큰 감흥은 없긴 하네요.
그래도 꾸준히 뭔가 하신 분들의 열정으로 여기까지 올 수 있었던 거라 생각합니다.
이번 회차에 출석하면 기존 전달했던 스타벅스 아메리카노 대신
아래 `행복을 선물해요` 세트를 드리도록 하겠습니다.
혼자 먹기에는 어려울 수 있으므로 19,900원 스타벅스 금액권이라고 생각하는게 더 나을 수 있습니다.

![image](https://github.com/user-attachments/assets/9515e71c-d179-4bec-b5cc-00f078753702)

**Comment by fkdl0048** [comment]
200회라니.. 좋은 쉼터? 만들어주셔서 정말 감사합니다.

### 할일

- https://github.com/fkdl0048/BookReview/issues/276

### 받고 싶은 책

- [우리는 왜 게임을 하는가?](https://www.yes24.com/Product/Goods/132617063)

**Comment by yeslee-v** [comment]
대망의 200회라니..!!! 함께할 수 있어 영광입니다~~
더불어 다들 추석 연휴 잘 보내세요~~ (미리 인사드립니다)

## To do 

- 토이프로젝트 3주차 회고 포스팅

**Comment by aquamagic9** [comment]
200회가 될 동안 꾸준하게 지속해주셔서 감사합니다!
이런 꾸준함을 본받아야겠네요.
## 할 일
프로그래머의 길, 멘토에게 묻다 81p ~ 148p까지 정리하기

**Comment by chichoon** [comment]
## 할 일

자바스크립트 딥다이브 14 장 전역변수의 문제점 읽기

12시 20분 쯤 나와야 할 수 있습니다 ㅜ_ㅜ

---

100 회가 얼마전 같은데 벌써 200 회라니 두 회차 모두 참여할 수 있어서 감격 스럽네요...

300회 400회에도 참여해서 부동의 1위 지켜내겠습니다 즐추입니다 🫡🫡

**Comment by ohdair** [comment]
200회 참여하면서 집중하는 시간을 가질 수 있어서 좋았어요!
앞으로도 꾸준히 참여할게요 :)

### 할 일
[TMI: 정보가 너무 많아서](https://product.kyobobook.co.kr/detail/S000211708372) 독서
데이터분석 관련 방법 정리

**Comment by jongfeel** [comment]
## [도메인 주도 설계](http://aladin.kr/p/p6ehn) 읽고 정리하기

- https://github.com/jongfeel/BookReview/issues/896
  - https://github.com/jongfeel/BookReview/issues/912

14장 모델의 무결성 유지
CONTEXT MAP 부분 읽고 정리
SHARED KERNEL 부분 읽고 정리
