### ISSUE TITLE
40th online meetup, 2021-08-21, special promotion: Iced Starbucks Dolce Latte

### ISSUE THREAD

**Issue by jongfeel** [ThinkAboutSoftware/OnlineSelfCodingGroup#76]
https://meet.google.com/jyx-mxnq-kpk

### 참여 방법:

Assignees에 자신의 github 계정을 self로 추가
2시간 분량의 할 내용에 대해 댓글 작성 (최소 모임 시작 전까지)
빛의 속도 혹은 (주말, 휴일 포함) 최소 3일 내에 구글 캘린더 등록 메일 확인
모임 시간에 각자 개발 관련된 공부 진행

- 시작: 10시 30분
- 시작 토크: 10시 40분까지
- 공부 진행: 12시 30분 종료
- 마무리 토크: 최대한 12시 40분까지, 조금 오버할 수 있음 (오래 하면 30분 얘기하기도 함)

모임 끝난 후 공부한 내용 정리 & 링크 추가 => 최소 다음 모각코 전까지 확인 가능해야 함.

**주의: 회사일 혹은 마감 기한 임박한 일 처리의 경우는 최대한 자제해 주세요. 주말 아침에 일하면 우울하니까요. ㅜㅜ**

### Special promotion

어느덧 40회가 되었네요.
다 여러분들이 참여한 덕분에 방폭파가 한번도 되지 않고 여기까지 온 것 같습니다.
지난 번과 마찬가지로 10으로 나눈 나머지가 0이 되는 회차 기념으로 스페셜 프로모션을 준비했습니다.
이번 모임 참석을 포함해서 4회 참석을 달성하시면 아이스 스타벅스 돌체 라뗴로 음료가 업그레이드 됩니다.
언젠가 아이스 스타벅스 돌체 라떼로 업그레이드된 음료를 받고 싶으신 분은 이번 모임에 참여해서 꼭 스탬프를 찍으시면 됩니다. 
![image](https://user-images.githubusercontent.com/17442457/129702642-cdbc83e9-af77-400c-9abb-77163edf0ec2.png)

**Comment by ellen310** [comment]
SpartaCodingClub 게임개발 4주차 공부 및 개발일지 작성
스플래시 추가, UGUI살펴보기, UGUI버튼 및 동작 실습, 팝업 기능
https://www.notion.so/teamsparta/4-a587e2d220224c809ebca5b23cb3c48c

**Comment by ErigoLee** [comment]
백준 2458번 문제 풀기
https://www.acmicpc.net/problem/2458
프로그래머스 문제 풀기
https://programmers.co.kr/learn/courses/30/lessons/72414

**Comment by wjrmffldrhrl** [comment]
# Fluent Python
## 제어 흐름
### Future를 이용한 동시성.
- Python 특유의 동시성 프로그래밍 이해
- GIL 이해

**Comment by ShimWooJeong** [comment]
진행중인 한이음 프로젝트(AR/VR 과학 실험) 저번주 오류 해결 + 핸드트래킹 인식 성공
핸드트래킹으로 오브젝트를 집거나, UI를 클릭하는 등의 동작을 구현할 예정

**Comment by Joseph-Cha** [comment]
따배 C++ 강의 수강
- 6.12 ~ 6.16(5강)

**Comment by eunyeong-so** [comment]
**할일**
Game Player, Monster 객체 상호작용을 고려해 인터페이스 설계

**Comment by jongfeel** [comment]
책을 늦게 읽어서 늦게나마 올려 봅니다.

## [오브젝트](https://github.com/jongfeel/objects)

### Chapter05 책임 할당하기

- 01 책임 주도 설계를 향해
- 02 책임 할당을 위한 GRASP 패턴

133p ~ 145p
