### ISSUE TITLE
50th online meetup, 2021-10-30 with special promotion: 바라는대로 세트

### ISSUE THREAD

**Issue by jongfeel** [ThinkAboutSoftware/OnlineSelfCodingGroup#88]
https://meet.google.com/jyx-mxnq-kpk

### 참여 방법:

Assignees에 자신의 github 계정을 self로 추가
2시간 분량의 할 내용에 대해 댓글 작성 (최소 모임 시작 전까지)
빛의 속도 혹은 (주말, 휴일 포함) 최소 3일 내에 구글 캘린더 등록 메일 확인
모임 시간에 각자 개발 관련된 공부 진행

- 시작: 10시 30분
- 시작 토크: 10시 40분까지
- 공부 진행: 12시 30분 종료
- 마무리 토크: 최대한 12시 40분까지, 조금 오버할 수 있음 (오래 하면 30분 얘기하기도 함)

모임 끝난 후 공부한 내용 정리 & 링크 추가 => 최소 다음 모각코 전까지 확인 가능해야 함.

**주의: 회사일 혹은 마감 기한 임박한 일 처리의 경우는 최대한 자제해 주세요. 주말 아침에 일하면 우울하니까요. ㅜㅜ**

### Special promotion

최근 모임이 폭파될 뻔한 위기가 찾아왔음에도 불구하고, 50회 까지 살아 남았습니다.
우선 50회 까지 달려올 수 있는 것만으로도 기뻐해야 할 일일 것 같네요.
지난 번과 마찬가지로 10으로 나눈 나머지가 0이 되는 회차 기념으로 스페셜 프로모션을 준비했습니다.
이번 모임 참석을 포함해서 4회 참석을 달성하시면 `가을 타는 너를 위한 세트`로 업그레이드 됩니다.
할로윈 데이를 맞이해서 스타벅스에서 만든 세트 메뉴인데 할로윈이 지나도 같은 가격대에 아무거나 드실 수 있을 겁니다.
엄청난 세트 메뉴를 준비했으니 이번 회차에는 많이 참석하기를 기대해 봅니다!

---

모각코 끝나고 gift item을 드릴려고 하다 보니 할로윈 행사가 끝났는지 제가 처음에 드린다고 했던 item이 사라져 버렸습니다. ㅜㅜ

그래서 `바라는대로 세트`로 바꿔서 드렸어요

![image](https://user-images.githubusercontent.com/17442457/140299975-5ef01c26-6ed1-4d07-bfb8-d7d30495d440.png)

**Comment by ShimWooJeong** [comment]
## 게임개발 종합반 5주차 수강
- 가상 조이스틱 구현
- 입력 관리자 바꾸기
- 앱 빌드해보기
- Unity Ads를 통해 광고 붙이기

**Comment by eunyeong-so** [comment]
## 할일 
- 몬스터 움직임 패턴 여러개 생성
- 몬스터 spawn 방식에 대한 고민

**Comment by jongfeel** [comment]
### [Rapid Development](http://aladin.kr/p/8F8EV)

고전 책 읽기
5장 위험 관리
노션에 내용 정리

---
