### ISSUE TITLE
60th online meetup, 2021-01-08 with special promotion: `New year citrus tea`

### ISSUE THREAD

**Issue by jongfeel** [ThinkAboutSoftware/OnlineSelfCodingGroup#98]
https://meet.google.com/jyx-mxnq-kpk

### 참여 방법:

Assignees에 자신의 github 계정을 self로 추가
2시간 분량의 할 내용에 대해 댓글 작성 (최소 모임 시작 전까지)
빛의 속도 혹은 (주말, 휴일 포함) 최소 3일 내에 구글 캘린더 등록 메일 확인
모임 시간에 각자 개발 관련된 공부 진행

- 시작: 10시 30분
- 시작 토크: 10시 40분까지
- 공부 진행: 12시 30분 종료
- 마무리 토크: 최대한 12시 40분까지, 조금 오버할 수 있음 (오래 하면 30분 얘기하기도 함)

모임 끝난 후 공부한 내용 정리 & 링크 추가 => 최소 다음 모각코 전까지 확인 가능해야 함.

**주의: 회사일 혹은 마감 기한 임박한 일 처리의 경우는 최대한 자제해 주세요. 주말 아침에 일하면 우울하니까요. ㅜㅜ**

---

### Special promotion

드디어 60회 까지 왔습니다. 58회 때 폭파 위기가 왔지만 크리스마스 특수를 감안하여 계속 진행하기로 했습니다.
지난 번과 마찬가지로 10으로 나눈 나머지가 0이 되는 회차 기념으로 스페셜 프로모션을 준비했습니다.
이번 모임 참석을 포함해서 4회 참석을 달성하시면 새해를 맞이해서 스타벅스에서 판매하는 `뉴이어 시트러스 티`로 업그레이드 해서 드립니다.

<img width="833" alt="image" src="https://user-images.githubusercontent.com/17442457/147844386-d568f0ec-454b-4095-94d0-59d1a06aeffa.png">

**Comment by JSY8869** [comment]
### 독서!
[객체지향 사고 프로세스](http://www.yes24.com/Product/Goods/90688759) 읽으면서 notion에 정리하기

**Comment by wisdom08** [comment]
- [ ] [자바 병렬 프로그래밍 ](http://www.yes24.com/Product/Goods/3015162) 3장 객체 공유 파트 읽고 노션 정리

- [ ] text based RPG game 자바로 만든 거 멀티스레드 추가해보기

**Comment by Joseph-Cha** [comment]
### 함께 자리기 독서

**Comment by jongfeel** [comment]
### Clean coder, chapter12 함께 일하기

Academic conference 2021에서 마저 못했던 내용에 대해 책 읽고 pull request 주기
https://github.com/ThinkAboutSoftware/AcademicConference/pull/87
